---
title: "Base de datos"
author: "Carla Mendoza"
date: "10/13/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

En este documento uniremos las datas trabajadas individualmente por los miembros del equipo.

Primero, Cargaremos todas las bases de datos
```{r}
LinkAri="https://raw.githubusercontent.com/AriannaNKZC/TrabajoGrupal/master/Entregables/Data_Final.csv"
Ari=import(LinkAri)

LinkCarla="https://raw.githubusercontent.com/CarlaMendozaE/EstadCarla/master/Carla.csv"
Carla=import(LinkCarla)

LinkCarlos="https://raw.githubusercontent.com/CarlosGDiez/BasesLimpias/master/dataFINAL.csv"
Carlos=import(LinkCarlos)

LinkMajo="https://raw.githubusercontent.com/MariaJoseVega/Trabajo-grupal-2020.2/master/DORIME.csv"
Majo=import(LinkMajo)
```

Homogenizamos los nombres
```{r}
names(Ari)[1]="Code"
names(Carlos)[1]="Code"
names(Carlos)[3]="Día7"
```

Combinamos las datas
```{r}
Data=merge(Carla, Ari, by.x = "Code", by.y = "Code")
Data=merge(Data, Carlos, by.x = "Code", by.y = "Code")
Data=merge(Data, Majo, by.x = "Code", by.y = "Code")
```

Eliminamos lo que no sirve
```{r}
Data[,14:15]=NULL
Data= Data[-c(43:66),]
```

Nos quedamos con la Data en un CSV.
```{r}
write.csv(Data,"Data.csv", row.names = F)
```

